# Generated by Django 4.1.1 on 2022-09-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service_provider",
            name="gallery",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.gallery"
            ),
        ),
        migrations.AlterField(
            model_name="service_provider",
            name="reviews",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="app.review"
            ),
        ),
        migrations.AlterField(
            model_name="service_provider",
            name="services_rendered",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="app.service"
            ),
        ),
    ]
