# Generated by Django 4.1.1 on 2022-09-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service_provider",
            name="gallery",
        ),
        migrations.RemoveField(
            model_name="service_provider",
            name="reviews",
        ),
        migrations.AlterField(
            model_name="service_provider",
            name="address",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="service_provider",
            name="avatar",
            field=models.CharField(
                blank=True, max_length=999, null=True, verbose_name="SP Picture/Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="service_provider",
            name="pitch",
            field=models.CharField(
                blank=True, max_length=999, null=True, verbose_name="Pitch"
            ),
        ),
        migrations.AlterField(
            model_name="service_provider",
            name="state",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="State"
            ),
        ),
    ]
