# Generated by Django 4.1.1 on 2022-09-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_service_provider_gallery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_avatar",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Service Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="sub_service",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.sub_service",
            ),
        ),
    ]
