# Generated by Django 4.1.1 on 2022-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_service_service_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_name",
            field=models.TextField(max_length=20, verbose_name="Service Name"),
        ),
    ]
