# Generated by Django 4.1.1 on 2022-09-23 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_client_address_alter_client_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_list",
                    models.TextField(max_length=200, verbose_name="Service List"),
                ),
                (
                    "client_id",
                    models.TextField(max_length=999, verbose_name="Client ID"),
                ),
                ("sp_id", models.TextField(max_length=999, verbose_name="Provider ID")),
                (
                    "service",
                    models.TextField(max_length=999, verbose_name="Main Service"),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, verbose_name="Quantity/Units"),
                ),
                (
                    "payment_mode",
                    models.TextField(
                        max_length=99, verbose_name="Payment mode (cash/wallet)"
                    ),
                ),
                (
                    "amount",
                    models.TextField(max_length=99, verbose_name="Total amount"),
                ),
                (
                    "service_address",
                    models.TextField(
                        max_length=99,
                        verbose_name="Address where service is/was rendered",
                    ),
                ),
                (
                    "client_paid",
                    models.BooleanField(default=False, verbose_name="Client Paid"),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "Service_Resquests_Table",
            },
        ),
    ]
