# Generated by Django 4.1.1 on 2022-09-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_service_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sub_service",
            name="main_service_id",
            field=models.TextField(
                blank=True, max_length=20, verbose_name="Main Service ID"
            ),
        ),
        migrations.AlterField(
            model_name="sub_service",
            name="name",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Sub_Service name"
            ),
        ),
        migrations.AlterField(
            model_name="sub_service",
            name="price",
            field=models.TextField(
                blank=True, max_length=999, verbose_name="Prove of Service"
            ),
        ),
    ]
