# Generated by Django 4.1.1 on 2022-09-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_sub_service_main_service_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="sub_service",
        ),
        migrations.AlterField(
            model_name="sub_service",
            name="price",
            field=models.TextField(blank=True, max_length=999, verbose_name="Amount"),
        ),
    ]
